### ISSUE TITLE
uBlock Origin无法检测

### ISSUE THREAD

**Issue by ttttmr** [neargle/ChromeExtensionKnower#4]
上个星期也在研究这个，自己写了个差不多的爬虫和构建检测规则的程序，看到有人star，点进来发现自己已经star了，又重复劳动了

在跑uBlock Origin的时候，看到的一个防御技术，分享一下

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

有`"web_accessible_resources": [ "/web_accessible_resources/*" ]`

`web_accessible_resources`里面有不少文件，比如`noop.js`文件

检测url应该是`chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/noop.js`

但是实际上访问不了`web_accessible_resources`里面的资源

```js
fetch("chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/noop.js")
```

报错是`net::ERR_BLOCKED_BY_CLIENT`，而其他访问不存在的war资源应该是`net::ERR_FAILED`

翻了下uBlock专门做了防御，所以没法检测，很强

https://github.com/gorhill/uBlock/issues/2823#issuecomment-366261107

> I worked around this issue by requiring a fetch to any of the web accessible resources ("WAR") to be made with a valid secret token -- which secret token is initialized at extension launch time with a random value.
>
> As long as the WAR are only used internally extension-side, and never exposed to the DOM, then I see no way for the web pages to be able to see these WAR, and thus no way to directly detect the extension through its WAR.
>
> The access to the content of the /web_accessible_resources/ folder is controlled by a webRequest.onBeforeRequest listener. The listener will redirect to a non-web accessible resource when it fails to find the secret in the URL of the resource being fetched.

**Comment by neargle** [comment]
太强了，Chrome 扩展也支持了新的特性以帮助开发者防御这里的问题。

即 web_accessible_resources 添加了 matches 白名单，仅在白名单范围内的url可以访问 web_accessible_resources，避免了前端指纹检测。但在我今年爬下来的插件中，仅有 286 个插件添加了 web_accessible_resources matches 白名单；而且还有绝大一部分配置了 *://*/* 这种无用白名单和其他明显可以绕过的白名单策略。

![image](https://user-images.githubusercontent.com/7868679/143674140-f6336277-7679-48b3-9a64-d94f011bfea3.png)

> A list of URL match patterns specifying which pages can access the resources. Only the origin is used to match URLs; subdomains patterns (*.google.com) and paths are ignored.

**Comment by neargle** [comment]
如果你感兴趣的话，也可以加个即时通讯的好友一起交流~

**Comment by ttttmr** [comment]
> 如果你感兴趣的话，也可以加个即时通讯的好友一起交流~

https://tmp.xlab.app/DB0A1093-4324-40E5-9B0D-16EDD4050154.jpeg
